# .cpanel.yml
---
deployment:
  tasks:
    - export PATH="/opt/cpanel/ea-nodejs20/bin:$PATH"
    - cd /home/unhscoke/repositories/jubilant
    - npm ci
    - npm run build
    - /bin/rsync -a --delete dist/ /home/unhscoke/public_html/
