# .cpanel.yml
---
deployment:
  tasks:
    - set -euo pipefail
    - export PATH="/opt/cpanel/ea-nodejs20/bin:$PATH"
    - node -v && npm -v
    - cd /home/unhscoke/repositories/jubilant
    - npm ci --no-audit --no-fund --progress=false
    - npm run build
    - /bin/rsync -ah --delete dist/ /home/unhscoke/public_html/
